# Key Findings
## Data Assessment:

-   While the crash data provided important insights, several characteristics or trends in crashes were not discernible from the data. To supplement the data, the study team scanned crash narratives from police reports of crashes. These provided clearer details in some cases, especially related to the pre-crash positioning of bicyclists and vehicles and sidewalk bicycling. While officer narratives are not always the most reliable source of information for pedestrian and bicyclist crash factors, keyword searching on their narratives proved useful to add nuance where roadway data were limited or coded crash report variables were ambiguous.

## Descriptive Crash Analysis:

-   **Injury Severity**:
    -   Bicyclist: There were 2,694 reported bicycle crashes during 2018–2022. Roughly 12% of those crashes were reported to be fatal or result in a serious injury.
    -   Pedestrians: During the same period, there were 4,131 reported pedestrian and other VRU crashes, with 24% resulting in a fatal or serious injury, twice the percentage of KA crashes than bicyclist crashes.
-   **Area Land Development Intensity**:
    -   Bicyclist: Most bicyclist crashes (37.4%) and KA crashes (36.6%) occurred within the TCMA - Other Cities areas, followed by TCMA - Minneapolis and St. Paul areas (36.8% of all crashes; 30.2% of KA crashes). Small urban communities (defined as rural downtown in SPACE) had the third largest share of crashes (13.1%) and KA crashes (12.9%).
    -   Pedestrians: Most pedestrian and other VRU crashes (46.9%) and KA crashes (34.9%) occurred within the TCMA - Minneapolis and St. Paul areas, which is likely related to the walkability of those communities and generally higher levels of pedestrian exposure. Additionally, crashes and KA crashes were heavily concentrated in these two cities on a per square mile basis. TCMA - Other Cities had the second highest share of crashes 27.7% and KA crashes 31.4%. Both of the communities accounted for 74.7% of all crashes and 66.2%, which mirrors the bicyclist findings.
-   **Month**:
    -   Bicyclist: In general, there were more bicycle crashes during warmer months (June through September).
    -   Pedestrian: The distribution of crashes is not as heavily concentrated during summer months for pedestrians as it is for bicyclist crashes. Pedestrian crashes and KA crashes instead appear slightly more concentrated in the early fall.
-   **Lighting Condition**:
    -   Bicyclist and Pedestrians: Most of the crashes happened in well-lit conditions, although KA crashes are slightly overrepresented in dark and low-light conditions. Both dark conditions with no street lighting and sunrise/sunset hours appear to be especially severe for people walking, rolling, and riding bicycles.
-   **Age**:
    -   Bicyclist: When comparing the distribution of victims by age to the state’s population, younger bicyclists are much more likely to be involved in a crash and a KA crash compared to older populations. Bicyclists aged 10-19 were the most overrepresented in crashes and bicyclists aged 15-19 were the most overrepresented in KA crashes.
    -   Pedestrians: Pedestrians aged between 15 through 34 generally had the highest share of victims involved in a crash with victims aged 20-24 accounting for the largest share of victims. Pedestrians aged between 15-29 and 55-59 were the most overrepresented, and KA victims and pedestrians under 15 years of age were the most underrepresented victims.
-   **Crash Location Type**:
    -   Bicyclist: Overall crashes and KA crashes occurred most frequently at stop-controlled intersections (40.2% of all crashes; 34.5% of KA crashes). Other findings in this study confirm that these are likely partial stop-controlled intersections, and not all-way stop- controlled intersections. This may be a systemic issue across the state, with bicyclists riding along lower-intensity streets (often residential streets) needing to cross major streets at partial stop-controlled intersections. This combination of lower-stress streets without crossing accommodations likely contributes to bicyclists attempting to cross a major street and being struck by a motorist who does not have a traffic control device.
    -   Pedestrians: Roughly two thirds of pedestrian crashes occurred at or near intersections regardless of intersection control. Crashes occurred most frequently at signalized intersection locations followed by segment (i.e, midblock) locations. Crashes tend to be more severe at midblock locations than intersection locations regardless of intersection control.
-   **MnDOT Trunk Highways**:
    -   Bicyclist: Crashes along trunk highways appear to be more severe in both urban and rural areas than crashes off the trunk highway system, but the patterns may be especially significant for rural areas. A large share of crashes occurs on four-lane trunk highways, and they carry this safety burden even when they have low AADT. Even if cyclists are not traveling along these locations, they may need to cross them, as these highways cut through urban areas and become main streets in smaller towns.
    -   Pedestrians: The results are similar to bicyclist crash trends with most crashes having occurred off the trunk highway system (81.5%, n=3,367), though there was a slightly larger percentage of pedestrian crashes and KA crashes that occurred along trunk highways compared to bicyclist crashes. Additionally, crashes that did occur along the trunk highway system resulted in more severe outcomes (30.5% resulted in a KA) compared to crashes that were not along the trunk highway system (22.9%).
-   **Trunk Highways – Urban/Rural**:
    -   Bicyclist: Most bicycle crashes happened off of the trunk highway system within Minneapolis and St. Paul, which makes sense, as there are likely more cyclists in Minneapolis and St. Paul than in other locations in the state, and there are proportionally fewer trunk highways and more locally owned roadways in these cities. Interestingly, most KA crashes both on and off the trunk highway network within the TCMA metro occurred in the surrounding suburban communities. For crashes that did occur along the trunk highway system, they most frequently occurred within small urban communities.
    -   Pedestrians: Like bicyclist crashes, a larger share of pedestrian crashes occurred along the trunk network in small urban communities (34.0%) compared to TCMA and greater MN metro areas (12.9% - 18.3%). More than half of the pedestrian crashes (56.1%) that did occur along the trunk highway network resulted in a KA outcome within the rural context, nearly three times the rate for pedestrian crashes in the TCMA Minneapolis and St. Paul area (18.4%).
-   **Trunk Highways – Sidewalks**:
    -   Bicyclist: Most severe crashes occurred along trunk highways that lacked a sidewalk and where there was no indication that the bicyclist was riding along the sidewalk (50% of KA crashes) – many of these crashes would likely have been prevented if the cyclist had been separated from vehicular traffic.
-   **Sidewalks**:
    -   Bicyclist: Often cyclists may be using sidewalk infrastructure to avoid bicycling on high speed or uncomfortable facilities, especially for younger cyclists and especially on trunk highways. While sidewalk riding is believed to pose a safety risk for bicyclists at intersections, bicycling on sidewalks may be the best choice people have to mitigate their overall risk in the absence of dedicated bicycle facilities. Sidewalk riding appears to be more common on high-risk facilities where there are large shares of serious injury and fatal crashes, so prohibiting sidewalk riding or enforcing sidewalk riding bans could potentially increase crashes and injury severity outcomes. Sidewalk bicycle riding points to the need for more infrastructure that facilitates safe and comfortable riding for people with different levels of bicycling confidence. Bicyclist crashes that occurred along trunk highways most frequently occurred if the bicyclist was using the sidewalk rather than riding within the road (40%). This is not surprising given that most trunk highways lack low-stress on-street bicycle facilities designed to encourage bicyclists of all ages and abilities to ride within the road rather than on the sidewalk. Furthermore, the need for these low-stress facilities is not just preference- based: most trunk highway severe crashes occurred along trunk highways that lacked a sidewalk and where there was no indication that the bicyclist was riding along the sidewalk (50% of KA crashes) – many of these crashes would likely have been prevented if the cyclist had been separated from vehicular traffic.
-   **Hit and Run**:
    -   Bicyclist: Most bicycle crashes (86.9%) and KA crashes (91.1%) were not hit and run. The distribution of hit-and-run crashes was similar between most urban and rural areas in terms of the percentage of crashes and severe crashes that were hit-and-run. However, TCMA Minneapolis and St. Paul had the largest relative share of hit-and-run responses for all crashes (24.1%) and KA crashes (18.8%).
    -   Pedestrians: Like bicyclist crashes, most pedestrian crashes (79.7%) and KA crashes (82.2%) were not hit and run. TCMA Minneapolis and St. Paul had an alarmingly high relative share of hit and run crashes (31.0%) and KA crashes (32.7%).
-   **Functional Classification**:
    -   Bicyclist: More than half of all crashes (52.1%) and KA crashes (50.5%) occurred on minor arterial. Since minor arterials comprise much less of the state’s roadway mileage, this indicates a serious safety issue with these roadways. Local roadways and major collectors had the next two largest shares of crashes and KA crashes. Minor arterials also have the highest number of crashes per mile for both all crashes (7.6 crashes per 100 miles) and KA crashes (0.9 KA crashes per 100 miles), followed by principal arterials (2.8 crashes per 100 miles; 0.4 KA crashes per 100 miles).
    -   Pedestrians: Pedestrian crashes (52.7%) and KA crashes (49.0%) occurred most frequently along minor arterials, followed by local roadways and major collectors. When looking at crashes on a per mile basis, minor arterials had the highest rate of crashes per 100 miles for all crashes (11.8 crashes per 100 miles) and KA crashes (2.7 KA crashes per 100 miles), followed by principal arterials (3.5 crashes per 100 miles; 1.1 KA crashes per 100 miles).
-   **Functional Classification Intersections**:
    -   Bicyclist: Most crashes (30.2%) and KA crashes (29.7%) occurred at intersections between minor arterials and local streets followed by major collectors and local streets (14% of all intersection crashes). Nearly half of all crashes (48%) and more than half of KA crashes (56%) indicate the bicyclist was cycling across traffic/roadway. Looking only at crashes at these locations with this crossing pre-crash action, 60% of crashes and 68% of KA crashes were at an intersection with some type of stop control (most likely two- way stop signs with the major street uncontrolled). This indicates an important safety issue at locations in which bicyclists are attempting to cross a major street but do not have a traffic control or crossing enhancement to facilitate a safe crossing.
    -   Pedestrians: Most crashes (30.8%) and KA crashes (30.3%) occurred at intersections between minor arterials and local streets, followed by minor arterials and minor arterials (15.2% of all intersection crashes) and minor arterials and major collectors (14.4% of all intersection crashes).
-   **Number of Through Lanes**:
    -   Bicyclist: Most crashes occur on two- and four-lane roadways. Roadways with five or more lanes had the most severe crashes with 13.8% crashes resulting in a KA outcome.
    -   Pedestrians: Most crashes occurred along two- and four-laned roads. One- and three-laned roads had the lowest share of crashes and KA crashes, which are likely related to there being fewer streets with one or three lanes, however crashes at these locations had the lowest proportion of crashes that resulted in a KA outcome.
-   **Speed limit**:
    -   Bicyclist: Most crashes (52.1%) and KA crashes (45.8%) occurred in places where there are 30mph speed limits. This could be due to several possible reasons, such as the prevalence of roadways where the posted speed limit is 30mph or a perception by cyclists that roadways with 30 mph speed limits are “low enough” stress for riding. However, there are notably fewer crashes and KA crashes on roadways signed at 25 mph or lower. Note that the crash data used in this analysis predates the legislative action in 2020 that allowed communities to lower speed limits on many locally-owned roads, so relatively few roads in the state had speed limits lower than 30 mph for crashes in this study.
    -   Pedestrians: Streets with a posted speed limit of 30 mph had the largest share of all crashes (59.9%) and largest share of KA crashes (51.6%). Streets with a speed limit of 50+ had the second largest share of KA crashes (10.9%) and the second largest share of all crashes (18.5%). The data show us that, as the posted speed limit increase, the proportion of crashes that resulted in a KA also increases.
-   **Traffic Volume**[^02-01_key_findings-1]:
    -   Bicyclist and Pedestrians: The relationship between bicyclist/pedestrian safety and motorist volumes is complex and nonlinear. Areas with the highest motorist volumes have relatively fewer bicyclist crashes. Mid-range AADT areas (5k-15k) appear to have the greatest concentrations of bike crashes.

[^02-01_key_findings-1]: Nearly 20% of bicyclist and pedestrian crashes and KA crashes occurred along streets without recorded AADT data.

-   **HERE – Entertainment, Retail, and Restaurants**:
    -   Bicyclist: Destinations such as entertainment establishments, retail, and restaurants appear to have some correlation with crashes, as 40.3% of all crashes were within 100 meters of one of the target destinations; however, only 35.4% of KA crashes were within this buffer.
    -   Pedestrians: Like bicyclist crashes, destinations appear to have some correlation with crashes, though the relationship appears to be slightly stronger for pedestrians with 48.3% of all crashes and 40.4% KA crashes within 100 meters of one of the target destinations.
-   **Presence of Transit near Intersection Crashes**:
    -   Bicyclist: There were no bicycle crashes in proximity to transit in the rural context. In larger urbanized areas, crashes in Minneapolis and St. Paul and severe crashes oftentimes occurred near transit stops or stations.
    -   Pedestrians: The percentage of pedestrian crashes and KA crashes that occurred near a transit stop is much higher for pedestrians than for bicyclists. This difference between modes is likely associated to higher pedestrian volumes and a higher frequency of pedestrians crossing the street to access a bus stop compared to bicyclists.
-   **SPACE Score**:
    -   Bicyclist and Pedestrians: Most crashes occurred in areas with mid-range SPACE scores. There appears to be an inverse correlation between the percentage of severe crashes and the SPACE score. This possible inverse correlation may be due to lower motor vehicle speeds in locations with higher SPACE scores (for example, due to congestion, existing roadway design, or lower posted speed limits) or greater motorist expectations of bicyclist or pedestrian presence.
-   **Equity**:
    -   Bicyclist and Pedestrians: While the majority of crashes happen outside of low-income and majority communities of color areas, areas where 40% or more of households are low-income and/or 50% or more of residents are POC have a greater concentration of crashes and severe crashes. While this pattern is strongest in Minneapolis and St. Paul, there is evidence of disparities across all geography groups – including small urban areas. Residents in low-income areas and communities of color are exposed to greater risk of crashes.
